version: '3'
networks:
  backend: null
  frontend: null
services:
  web-server:
    container_name: nginx
    platform: linux/amd64
    networks:
      - frontend
      - backend
    image: 'nginx:1.17'
    ports:
      - '${HTTPS_PORT}:443'
      - '${HTTP_PORT}:80'
    volumes:
      - './docker/log/nginx:/var/log/nginx'
      - './docker/nginx/conf:/etc/nginx/conf.d'
      - './docker/ssl:/etc/ssl'
      - './:/var/www/html/dibbling'
  node:
    container_name: node
    platform: linux/amd64
    networks:
      - frontend
      - backend
    restart: always
    image: 'node:13'
    ports:
      - '${DOCKER_NODE_PORT}:${DOCKER_NODE_PORT}'
    command: node /var/www/html/websocket.js
    volumes:
      - './docker/log/node:/var/log/node'
      - './docker/ssl:/etc/ssl'
      - './:/var/www/html'
  php-fpm:
    container_name: php
    platform: linux/amd64
    networks:
      - backend
    image: 'tinayork/php:8.0-fpm'
    expose:
      - 9000
    tty: true
    volumes:
      - './docker/php/conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini'
      - './docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini'
      - './docker/php/php-fpm.d:/usr/local/etc/php-fpm.d'
      - './docker/ssl:/etc/ssl'
      - './:/var/www/html/dibbling'
  database:
    container_name: mysql
    platform: linux/amd64
    networks:
      - backend
    ports:
      - '${DOCKER_DB_PORT}:3306'
    image: 'mysql:8.0.17'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - './docker/mysql/local.cnf:/etc/mysql/conf.d/local.cnf'
      - './docker/mysql/data:/var/lib/mysql'

#  # phpmyadmin
#  phpmyadmin:
#    container_name: phpmyadmin
#    image: phpmyadmin/phpmyadmin:4.8
#    networks:
#      - frontend
#      - backend
#    restart: always
#    ports:
#      - "8080:80"
#    environment:
#      PMA_HOST: ${DB_HOST}
#      PMA_PORT: ${DB_PORT}
#      PMA_USER: ${DB_USERNAME}
#      PMA_PASSWORD: ${DB_PASSWORD}
#
#  # PMA dibbling
#  pma_dibbling:
#    container_name: pma_dibbling
#    image: phpmyadmin/phpmyadmin:4.8
#    ports:
#      - "8081:80"
#    environment:
#      PMA_HOST: ${DB_HOST_PRO}
#      PMA_PORT: ${DB_PORT_PRO}
#      PMA_USER: ${DB_USERNAME_PRO}
#      PMA_PASSWORD: ${DB_PASSWORD_PRO}

#  # cache
#  cache:
#    container_name: redis
#    networks:
#      - backend
#    image: redis:5
#    ports:
#      - "6379:6379"
